module(load="imudp")
input(type="imudp" port="5514" ruleset="nmsRemote")
module(load="imtcp")
input(type="imtcp" port="5514" ruleset="nmsRemote")

template(name="NmsRemotePath" type="string" string="/var/log/nms-remote/%HOSTNAME%/%PROGRAMNAME%.log")
template(name="NmsRemoteForward" type="string" string="<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%msg%\n")

ruleset(name="nmsRemote") {
    action(type="omfile" dynaFile="NmsRemotePath" createDirs="on")
    if $fromhost-ip != "127.0.0.1" then {
        action(
            type="omfwd"
            target="192.168.1.33"
            port="5514"
            protocol="udp"
            template="NmsRemoteForward"
            action.resumeRetryCount="-1"
            queue.type="linkedList"
            queue.filename="nmsRemoteForward"
            queue.saveOnShutdown="on"
        )
    }
    stop
}
